org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric (https://fabricmc.net/develop)
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.4
loader_version=0.18.4
loom_version=1.14-SNAPSHOT
fabric_api_version=0.141.1+1.21.11

# Mod
mod_version=1.0.0
maven_group=com.sm1les.meowmur
archives_base_name=meowmur
